<?xml version="1.0" encoding="utf-8"?><Database Name="AutoLot" Class="AutoLotObjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=AutoLot;Integrated Security=True;Pooling=False" SettingsObjectName="LinqDataBaseAccess.Properties.Settings" SettingsPropertyName="AutoLotConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CreditRisks" Member="CreditRisks">
    <Type Name="CreditRisk">
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="CarID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Make" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PetName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Inventory_Order" Member="Orders" ThisKey="CarID" OtherKey="CarID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CarID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Inventory_Order" Member="Inventory" ThisKey="CarID" OtherKey="CarID" Type="Inventory" IsForeignKey="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustID" OtherKey="CustID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="CustID" OtherKey="CustID" Type="Order" />
    </Type>
  </Table>
</Database>